// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAkv9S2I8Sj3Ky9dZT0F79GNRDsTZFafo',
    appId: '1:172068142994:web:b89359a31a257cd3f60b4b',
    messagingSenderId: '172068142994',
    projectId: 'recipe-app-19b55',
    authDomain: 'recipe-app-19b55.firebaseapp.com',
    storageBucket: 'recipe-app-19b55.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHUEplguZFDudcSM3qDmDayRkeUf61yEg',
    appId: '1:172068142994:android:e6d6e07ccfd53548f60b4b',
    messagingSenderId: '172068142994',
    projectId: 'recipe-app-19b55',
    storageBucket: 'recipe-app-19b55.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHVuic1teibH7nXfrglFjnThjR6efoz4A',
    appId: '1:172068142994:ios:8b4a6a3f3efb1b2cf60b4b',
    messagingSenderId: '172068142994',
    projectId: 'recipe-app-19b55',
    storageBucket: 'recipe-app-19b55.firebasestorage.app',
    iosBundleId: 'com.example.misLab2201087',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHVuic1teibH7nXfrglFjnThjR6efoz4A',
    appId: '1:172068142994:ios:8b4a6a3f3efb1b2cf60b4b',
    messagingSenderId: '172068142994',
    projectId: 'recipe-app-19b55',
    storageBucket: 'recipe-app-19b55.firebasestorage.app',
    iosBundleId: 'com.example.misLab2201087',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAkv9S2I8Sj3Ky9dZT0F79GNRDsTZFafo',
    appId: '1:172068142994:web:8207aa18bd1c9e9df60b4b',
    messagingSenderId: '172068142994',
    projectId: 'recipe-app-19b55',
    authDomain: 'recipe-app-19b55.firebaseapp.com',
    storageBucket: 'recipe-app-19b55.firebasestorage.app',
  );

}